name: EssentiallyMisc
main: com.steamcraftmc.EssentiallyMisc.MainPlugin
version: '1.0'
author: rknapp
load: startup
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command> [message...]
    aliases: [away]
    permission: essentials.afk
    permission-message: '§4You do not have permission to use this command.'
    default: true
  me:
    description: Emotes the specified action in chat.
    usage: /<command> <action>
    aliases: [em]
    permission: essentials.me
    permission-message: '§4You do not have permission to use this command.'
    default: true
  hat:
    description: Get some cool new headgear.
    usage: /<command> [remove]
    aliases: []
    permission: essentials.hat
    permission-message: '§4You do not have permission to use this command.'
    default: op
  editsign:
    aliases: [edit,edittext]
    description: Changes a line of text on the sign you are looking at.
    usage: /<command> <line 1-4> new text line
    permission: essentials.signs.edit
    permission-message: '§4You do not have permission to use this command.'
    default: op
  near:
    description: Lists the players near by or around a player.
    usage: /<command> [radius]
    aliases: [nearby]
    permission: essentials.near
    permission-message: '§4You do not have permission to use this command.'
    default: op
  recipe:
    description: Display the recipe for an item.
    usage: /<command> <item>
    aliases: []
    permission: essentials.recipe
    permission-message: '§4You do not have permission to use this command.'
    default: true
  suicide:
    description: Prove your mortality.
    usage: /<command>
    aliases: []
    permission: essentials.suicide
    permission-message: '§4You do not have permission to use this command.'
    default: true
  workbench:
    description: Open and use a workbench.
    usage: /<command>
    aliases: [craft]
    permission: essentials.workbench
    permission-message: '§4You do not have permission to use this command.'
    default: op
  enderchest:
    description: Open and access your enderchest anywhere.
    usage: /<command>
    aliases: [echest]
    permission: essentials.enderchest
    permission-message: '§4You do not have permission to use this command.'
    default: true
